redhat-upgrade-tool(8)
========
:man source:  redhat-upgrade-tool
:man manual:  redhat-upgrade-tool User Manual

NAME
----
redhat-upgrade-tool - Red Hat Upgrade tool


SYNOPSIS
--------
redhat-upgrade-tool ['OPTIONS'] *SOURCE*

DESCRIPTION
-----------
*redhat-upgrade-tool* is the Red Hat Upgrade Tool.

The *redhat-upgrade-tool* client runs on the system to be upgraded. It determines what
packages are needed for upgrade and gathers them from the source(s) given.
It also fetches and sets up the boot images needed to run the upgrade and
sets up the system to perform the upgrade at next boot.

The actual upgrade takes place when the system is rebooted, using the boot
images set up by *redhat-upgrade-tool*. The upgrade initrd starts the existing system
(mostly) as normal, lets it mount all the local filesystems, then starts the
upgrade.

When the upgrade finishes, it reboots the system into the newly-upgraded OS.

OPTIONS
-------

Optional arguments
~~~~~~~~~~~~~~~~~~
*-h*, *--help*::
Show a help message and exit.

*-v*, *--verbose*::
Print more info.

*-d*, *--debug*::
Print lots of debugging info.

*--debuglog* 'DEBUGLOG'::
Write debugging output to the given file. Defaults to '/var/log/redhat-upgrade-tool.log'.

*--reboot*::
Automatically reboot to start the upgrade when ready.


SOURCE
~~~~~~

These options tell *redhat-upgrade-tool* where to look for the packages and boot images
needed to run the upgrade. At least one of these options is required.

*--device* ['DEV']::
Device or mountpoint of mounted install media. If 'DEV' is omitted, *redhat-upgrade-tool*
will scan all currently-mounted removable devices (USB disks, optical media,
etc.)

*--iso* 'ISO'::
Installation image file.

*--network* 'VERSION'::
Online repos matching 'VERSION' (a number or "rawhide")

Multiple sources may be used, if desired.


Additional options for *--network*
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

*--enablerepo* 'REPOID'::
Enable one or more repos (wildcards allowed).

*--disablerepo* 'REPOID'::
Disable one or more repos (wildcards allowed).

*--addrepo* 'REPOID=[@]URL'::
Add the repo at 'URL'. Prefix URL with '@' to indicate that the URL is a
mirrorlist.

*--instrepo* 'REPOID'::
Get upgrader boot images from the repo named 'REPOID'. The repo must contain a
valid '.treeinfo' file which points to the location of usable 'kernel' and
'upgrade' images.


Cleanup commands
~~~~~~~~~~~~~~~~

*--resetbootloader*::
Remove any modifications made to bootloader configuration.

*--clean*::
Clean up everything written by *redhat-upgrade-tool*.

EXAMPLES
--------

*redhat-upgrade-tool --network 7.0 --instrepo <repo URL>*

Upgrade to RHEL 7.0 by downloading all needed packages and data from the
specified repository.

*redhat-upgrade-tool --device --network 7.0*

Upgrade to RHEL 7.0 using install media mounted somewhere on the system,
fetching updates from the network if needed.

EXIT STATUS
-----------
0::
    Success.
1::
    Cancelled by user, failure writing files to disk, or other unknown error
2::
    Failed to download/copy files from the given 'SOURCE'
3::
    RPM upgrade transaction test failed

BUGS
----
The *--iso* image must be on a filesystem listed in '/etc/fstab'.

AUTHORS
-------
Will Woods <wwoods@redhat.com>

// vim: syn=asciidoc tw=78:
