redhat-upgrade-tool(8)
======================
:man source:  redhat-upgrade-tool
:man manual:  redhat-upgrade-tool User Manual

NAME
----
redhat-upgrade-tool - Red Hat Upgrade tool


SYNOPSIS
--------
redhat-upgrade-tool ['OPTIONS'] *SOURCE*

DESCRIPTION
-----------
*redhat-upgrade-tool* is the Red Hat Upgrade Tool.

The *redhat-upgrade-tool* client runs on the source system. It determines what
packages are needed for upgrade and gathers them from the given source(s).
It also fetches and sets up the boot images needed to run the upgrade and
sets up the system to perform the upgrade at next boot.

The actual upgrade occurs when the system is rebooted, using the boot
images set up by *redhat-upgrade-tool*. The upgrade initrd starts the source
system as normal, lets it mount all the local filesystems, and then starts the
upgrade.

When the upgrade finishes, it reboots the system into the newly-upgraded OS.

OPTIONS
-------

Optional arguments
~~~~~~~~~~~~~~~~~~
*-h*, *--help*::
Show a help message and exit.

*-v*, *--verbose*::
Print more info.

*-d*, *--debug*::
Print lots of debugging info.

*--debuglog* 'DEBUGLOG'::
Write debugging output to the given file. Defaults to '/var/log/redhat-upgrade-tool.log'.

*--reboot*::
Automatically reboot to start the upgrade when ready.


SOURCE
~~~~~~

These options provide *redhat-upgrade-tool* with the information where to look
for the packages and boot images needed to run the upgrade. At least one of
these options is required.

*--device* ['DEV']::
Device or mountpoint of mounted install media. If 'DEV' is omitted,
*redhat-upgrade-tool* will scan all currently-mounted removable devices
(for example USB disks and optical media).

*--iso* 'ISO'::
Installation image file.

*--network* 'RELEASEVER'::
Online repos. 'RELEASEVER' will be used to replace $releasever variable if it
occurs in some repo URL.

Multiple sources may be used, if desired.


Additional options for *--network*
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

*--enablerepo* 'REPOID'::
Enable one or more repos (wildcards are allowed).

*--disablerepo* 'REPOID'::
Disable one or more repos (wildcards are allowed).

*--addrepo* 'REPOID=[@]URL'::
Add the repo at 'URL'. Prefix URL with '@' to indicate that the URL is a
mirrorlist.

*--instrepo* 'REPOID'::
Get upgrader boot images from the repo named 'REPOID'. The repo must contain a
valid '.treeinfo' file, which points to the location of usable 'kernel' and
'upgrade' images.


Cleanup commands
~~~~~~~~~~~~~~~~

*--resetbootloader*::
Remove any modifications made to the bootloader configuration.

*--clean*::
Clean up everything written by *redhat-upgrade-tool*.

EXAMPLES
--------

*redhat-upgrade-tool --network 7.0 --instrepo <repo URL>*

Upgrade to RHEL 7.0 by downloading all needed packages and data from the
specified repository.

*redhat-upgrade-tool --device*

Upgrade the system by using installation media mounted on the system,
fetching updates from the network if needed.

EXIT STATUS
-----------
0::
    Success.
1::
    Cancelled by user, failure writing files to disk, or other unknown error
2::
    Failed to download/copy files from the given 'SOURCE'
3::
    RPM upgrade transaction test failed

BUGS
----
The *--iso* image must be on a filesystem listed in '/etc/fstab'.

AUTHORS
-------
Will Woods <wwoods@redhat.com>

// vim: syn=asciidoc tw=78:
